### ISSUE TITLE
Enh: expose the Events directly

### ISSUE THREAD

**Issue by rbtcollins** [andjo403/rs_tracing#6]
My use case - I'm tracing threaded IO code; I'm interested in the total time things take to complete, but there are many (hundreds potentially) of concurrent things outstanding from the main thread, so the trace_expr etc macros aren't suitable, but something where I stored the event along with my operation, and then submitted it on completion to the tracer would be just fine.

**Comment by rbtcollins** [comment]
To clarify a little - obviously I can trace within each thread, but tracing the time spent in queues etc is really quite tricky as those primitives naturally cross threads; start == insert into queue; end == taken out of queue by a worker.

**Comment by andjo403** [comment]
you also have the trace_begin/trace_end macros but they still expect the same thread I think according to the [docs ](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#) so then maybe you need the async events.

and then I need to clean up the event code have made some assumtions due to only the macros have been the "public" interface of the crate

**Comment by andjo403** [comment]
I do not want to expose any types from this crate due to I want to have the possibility to not generate any code when I do not set the feature flag so I only want macros in the public API

**Comment by rbtcollins** [comment]
Flow events are the type needed to cross threads (similar to async events, next one down in the docs).

re: code generation, I do understand the desire for being able to have zero-cost in an optimised build; but that doesn't preclude exporting the types to allow folk to write analysis tools in rust to process Event format types themselves etc - those are separate use cases.
